### ISSUE TITLE
Regarding Documentation

### ISSUE THREAD

**Issue by madhuakula** [PaloAltoNetworks/pandevice#1]
Hello @btorresgil 

Could you please update the documentation please ?

I checked the below link and couldn't found anything.
**https://pandevice.readthedocs.org**

Thanks !

**Comment by btorresgil** [comment]
Hi Madhu,

Thanks for your interest in the pandevice library.  The library is in rapid development and I'm looking forward to the first release on Pypy.  That first release will include documentation at readthedocs.org, but with so much development going on it will take some time before the first release is ready.

You're welcome to use the library in its current alpha state.  I've been adding examples scripts here:
https://github.com/PaloAltoNetworks-BD/pandevice/tree/master/examples

If you have questions while using the library, or have an interesting use case you'd like added, please contact me though my github profile and I'll be happy to help.

Thanks!
 -Brian

**Comment by madhuakula** [comment]
Thank you so much @btorresgil , Looking forward and love to contribute on some stuff.

**Comment by btorresgil** [comment]
Documentation added!

http://pandevice.readthedocs.org

Also first release to PyPI.

**Comment by madhuakula** [comment]
Thanks for the update.
