### ISSUE TITLE
Create Rules dont accept uppercase in zone_ip, destination IP and service

### ISSUE THREAD

**Issue by stephrobert** [PaloAltoNetworks/pandevice#110]
We create object with uppercase and when we use create_security_rule we obtains error from pandevice.policies

[2018-03-13 16:52:37,596] {#flaskit/resource.py:232} 100a688b ERROR -  datacenter -> pre-rulebase -> security -> rules -> Test1 -> source 
'['PHMBUPIAPIA']' is not an allowed keyword
 datacenter -> pre-rulebase -> security -> rules -> Test1 -> source ['PHMBUPIAPIA'] is an invalid ipv4/v6 address
 datacenter -> pre-rulebase -> security -> rules -> Test1 -> source '['PHMBUPIAPIA']' is not a valid reference
 datacenter -> pre-rulebase -> security -> rules -> Test1 -> source ['PHMBUPIAPIA'] range separator('-') not found
 datacenter -> pre-rulebase -> security -> rules -> Test1 -> source is invalid
Traceback (most recent call last):

**Comment by btorresgil** [comment]
Hello, can you share the code that leads to this error?

**Comment by stephrobert** [comment]
source_ip = ["DHMBUPIAPIA"] # Dyn Adress group
        destination_ip = ["PHMBUPIAPIA"] # Dyn adress group
        service = ["TCP_8443"]
        rulebase = apiPano.get_rulebase(destinationDeviceGroup)
        new_rule = apiPano.create_security_rule(
                    rule_name=ref,
                    description="Defined by API",
                    tags=None,
                    source_zone=["any"],
                    source_ip=source_ip,
                    source_user=None,
                    destination_zone=["any"],
                    destination_ip=destination_ip,
                    category=None,
                    application=["any"],
                    service=service,
                    hip_profiles=None,
                    group_profile=None,
                    antivirus=None,
                    vulnerability=None,
                    spyware=None,
                    url_filtering=None,
                    file_blocking=None,
                    data_filtering=None,
                    wildfire_analysis=None,
                    log_start=None,
                    log_end=None,
                    action="allow",
                    rule_type=None,
                    log_setting="default")
        apiPano.add_rule(rulebase, new_rule)

**Comment by btorresgil** [comment]
Are you sure you're on the right repo?  This pandevice library for python doesn't have any methods called `get_rulebase()` or `create_security_rule()`.  What library are you using?  Are you trying to use Ansible?

**Comment by stephrobert** [comment]
yes it's my fonction : 
    def create_security_rule(self, **kwargs):
        """Create Security rules."""
        security_rule = policies.SecurityRule(
            name=kwargs['rule_name'],
            description=kwargs['description'],
            fromzone=kwargs['source_zone'],
            source=kwargs['source_ip'],
            source_user=kwargs['source_user'],
            hip_profiles=kwargs['hip_profiles'],
            tozone=kwargs['destination_zone'],
            destination=kwargs['destination_ip'],
            application=kwargs['application'],
            service=kwargs['service'],
            category=kwargs['category'],
            log_start=kwargs['log_start'],
            log_end=kwargs['log_end'],
            action=kwargs['action'],
            type=kwargs['rule_type']
        )

**Comment by btorresgil** [comment]
I see.  The errors you're getting are coming from the Panorama which typically means the configuration you're trying to make is not valid.  pandevice doesn't check configuration for validity, it leaves that up to the firewall/Panorama.  This error stand out to me:

`'['PHMBUPIAPIA']' is not an allowed keyword`

The reference here is a string containing your array syntax.  So while the reference should be `'PHMBUPIAPIA'` it is instead arriving at the Panorama as `'['PHMBUPIAPIA']'`.  This means that somewhere in your code you are likely causing the array to be treated as a string instead of an array.  Since I don't have the full code its hard to say where this might be happening.  I tested the portions you gave me and it worked fine, so there must be some other code that is causing the problem.

Hope that helps you track down the source of the problem.

**Comment by stephrobert** [comment]
Thanks I ll check

Le 14 mars 2018 22:20, "Brian Torres-Gil" <notifications@github.com> a
écrit :

**Comment by stephrobert** [comment]
The problem is corrected !

**Comment by btorresgil** [comment]
Wonderful!  Very glad to hear it's working.
