### ISSUE TITLE
Methods download() and install() in SoftwareUpdater only perform action if sync=True.

### ISSUE THREAD

**Issue by mrichardson03** [PaloAltoNetworks/pandevice#111]
I've been writing some code for Ansible modules, and I've noticed the download and install methods in SoftwareUpdater only perform the action if the sync parameter is set to true:

(Install method displayed, download is similar.)
```
    def install(self, version, load_config=None, sync=False):
        self._logger.info("Device %s installing version: %s" % (self.pandevice.id, version))
        response = self._op('request system software install%s version "%s"' %
                            (" load-config " + load_config if load_config is not None else "",
                             version))
        if sync:
            result = self.pandevice.syncjob(response)
            if not result['success']:
                raise err.PanDeviceError("Device %s attempt to install version %s failed: %s" %
                                         (self.pandevice.id, version, result['messages']))
            return result
        else:
            return True
```

Is this intentional?

**Comment by btorresgil** [comment]
Hello.  The install action is actually taken by this line:

    response = self._op('request system software install%s version "%s"'...etc...

The part inside the `if sync` block is just to sync the job which waits until it completes and then verifies success.  So if `sync` is False, then the install operation will be kicked off, but the method will return immediately and never check that the install completed or succeeded.

Does that help clarify?

**Comment by mrichardson03** [comment]
Interesting.  Here's the code snippet I'm using:

```
        device = base.PanDevice.create_from_device(ip_address, username, password, api_key=api_key)
        device.software.check()

        if PanOSVersion(version) != PanOSVersion(device.version):
            device.software.download_install(version, sync=True)

            if restart:
                device.restart()
```

My guess is that since the download and install are being kicked off asynchronously if sync=False, I'm probably rebooting before the install completes.

**Comment by btorresgil** [comment]
He he, yeah that is possible.  You'll want sync=True so you wait until the install finishes before rebooting.  There is also this example script to work from which uses `upgrade_to_version()`.  This method handles all the software downloads, installs, and reboots necessary to go from the current version to the desired version:

https://github.com/PaloAltoNetworks/pandevice/blob/master/examples/upgrade.py
