### ISSUE TITLE
Need help in getting SecurityRules 

### ISSUE THREAD

**Issue by bangi123** [PaloAltoNetworks/pandevice#114]
Can you please add an example to get the list of policies.NatRule

**Comment by btorresgil** [comment]
You can use this example for `policies.SecurityRule`:
https://github.com/PaloAltoNetworks/pandevice/blob/develop/examples/ensure_security_rule.py

Just change `SecurityRule` to `NatRule`, they work the same way.

**Comment by btorresgil** [comment]
Glad it helps!  Credit to @shinmog for writing that one.  I'll close this issue but let us know if you have any feedback on the example or any other examples you'd like to see created.
