### ISSUE TITLE
Action "move" "set" etc 

### ISSUE THREAD

**Issue by aoprea1982** [PaloAltoNetworks/pandevice#115]
Hi guys,

The issue
======
After creating the security rule i need to move it on top on the rulebase.
Searched and tried a few things but could not do it. 

> How to move the policy using "pandevice" ?
> How to issue set commands on the firewall using "pandevice"?  Not using the preconfigured objects. 

What i tried
========
fw.op(cmd="configure")
fw.op("move rulebase security rules GP_To_Trust top")
fw.op(cmd="move rulebase security rules GP_To_Trust top")

The errror > /* pandevice.errors.PanDeviceXapiError:  configure  is unexpected */
                     /* pandevice.errors.PanDeviceXapiError:  move  is unexpected */

Thanks for helping.

**Comment by aoprea1982** [comment]
Tried also 

/// Command = '''
        <from>
            <member>Trust</member>
        </from>
        <to>
            <member>Untrust</member>
        </to>
        <source>
            <member>any</member>
        </source>
        <source-user>
            <member>any</member>
        </source-user>
        <category>
            <member>any</member>
        </category>
        <destination>
            <member>any</member>
        </destination>
        <application>
            <member>any</member>
        </application>
        <service>
            <member>any</member>
        </service>
        <hip-profiles>
            <member>any</member>
        </hip-profiles>
        <action>{action}</action>
        <description>{description}</description>
         '''

fw.op(cmd=Command, cmd_xml=False)
/// 

But Got 
/// 
pandevice.errors.PanDeviceXapiError:  operations  cannot have more than one subconfiguration

Please guys would help me?

**Comment by btorresgil** [comment]
Hello, Device Framework (pandevice) is an SDK that enhances the PAN-OS API, but it also allows you to use the PAN-OS API directly.  Currently we don't have any special functions for moving things in pandevice.  So you have 2 options:

1. Change the order of the rules and call `.apply_similar()` on one of them.  That will apply all the rules in the order you set them in pandevice.

2. Use the `move` API call that is part of the PAN-OS API.  Direct access to the PAN-OS API is available in pandevice in the `xapi` parameter of the `Firewall` or `Panorama` object.  For example:

    # assuming 'fw' is a Firewall object and 'some_rule' and 'another_rule' are SecurityRule objects
    fw.xapi.move(some_rule.xpath(), 'after', another_rule)

Here's the documentation for the 'move' api call:  https://github.com/kevinsteves/pan-python/blob/master/doc/pan.xapi.rst#movexpathnone-wherenone-dstnone

That all being said, I think it's worth wrapping the 'move' api in pandevice to simplify execution, similar to what we did with the `.op()` method.  Let's keep this issue open to track that enhancement.

**Comment by shinmog** [comment]
Ok, will add the following function:

`object.move(location, ref=None, update=True)`
