### ISSUE TITLE
Updating panorama template default_vsys after creation

### ISSUE THREAD

**Issue by DaveHewy** [PaloAltoNetworks/pandevice#137]
I cannot find a way to do this? Can someone point me in the right direction?
```
pandevice.errors.PanDeviceXapiError:  dev -> settings -> default-vsys 'vsys1' is not a valid reference
 dev -> settings -> default-vsys is invalid
```

**Comment by shinmog** [comment]
@DaveHewy 

Setting the default vsys in templates is weird.  The template definition must include one or more vsys specs, and your `default_vsys` must reference one of them.  In pandevice terms, this means that you must have a pandevice object tree that looks like this if you intend to set the default vsys:

`panorama.Panorama` > `panorama.Template` > `device.Vsys`

As long as your template has a `device.Vsys` child that matches what you want to set for the `panorama.Template.default_vsys`, you'll be fine.  You'll also note in my above example there does not need to be anything under the `device.Vsys`; it can be empty, but it must be present.

**Comment by DaveHewy** [comment]
@shinmog 
Weird indeed. Lets look at some code as im still struggling to see how this should fit together.

``
device = PanDevice.create_from_device(*auth)
template_name = 'dev'
template_list = Template.refreshall(device)
for template in template_list:
    if template.name == template_name:
        tpl = template
device = tpl
v = Vsys('None') # this is the current default vsys
device.add(v)
tpl.default_vsys='vsys1'
device.add(tpl)
tpl.apply() # hits max recursion error.
``

**Comment by shinmog** [comment]
Feel free to make the code look closer to what you have above if that's what you want, but something like this (plus exception catching):

```python
def myfunc():
    auth = ('192.168.1.1', 'admin', 'secret')
    template_name = 'dev'
    default_vsys = 'vsys1'

    # Open the connection and get all templates.
    con = PanDevice.create_from_device(*auth)
    templates = Template.refreshall(con)

    # Select the desired template to update.
    for tmpl in templates:
        if tmpl.name == template_name:
            break
    else:
        print('Template {0} not found'.format(template_name))
        return

    # Update the default vsys param.
    tmpl.default_vsys = default_vsys

    # Now make sure that if a default vsys is desired, there is a
    # pandevice.device.Vsys object present.
    if tmpl.default_vsys is not None:
        vsys_list = tmpl.findall(Vsys)
        for v in vsys_list:
            if v.name == default_vsys:
                break
        else:
            tmpl.add(Vsys(default_vsys))

    # Update the template.
    tmpl.apply()
```

**Comment by DaveHewy** [comment]
@shinmog with v.minor mods the example returns.

it might be worth noting the default vsys at editing is None. with the desired effect to set it to vsys1

```
>>> tmpl.apply()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david.heward/.virtualenvs/bgc_firewall/lib/python2.7/site-packages/pandevice/base.py", line 554, in apply
    device.active().xapi.edit(self.xpath(), self.element_str(), retry_on_peer=self.HA_SYNC)
  File "/home/david.heward/.virtualenvs/bgc_firewall/lib/python2.7/site-packages/pandevice/base.py", line 3253, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError: Malformed Request
```

**Comment by shinmog** [comment]
@DaveHewy 

Looking back at your second comment, you're hitting max recursion because you do `device = tpl`, then down below you do `device.add(tpl)` :)

> it might be worth noting the default vsys at editing is None. with the desired effect to set it to vsys1

I've just executed my code (changing the `auth` variable to real auth credentials) and it works.  I've tested it with:

1. the template doesn't exist
2. template exists and `default_vsys = None`
3. template exists and `default_vsys = 'vsys1'`

It works properly in all situations.  It seems like there is a problem in your translated version of the above example..?  Could you provide the code, please?

**Comment by DaveHewy** [comment]
@shinmog 
```
device = PanDevice.create_from_device(*auth)
template_name = 'dev'
default_vsys = 'vsys1'
templates = Template.refreshall(device)
for tmpl in templates:
    if tmpl.name == template_name:
        break
    else:
        print('Template {0} not found'.format(template_name))

tmpl.default_vsys = default_vsys
if tmpl.default_vsys is not None:
    vsys_list = tmpl.findall(Vsys)
    for v in vsys_list:
        if v.name == default_vsys:
            break
        else:
            tmpl.add(Vsys(default_vsys))
tmpl.apply()
```

results in

```
  File "<stdin>", line 1, in <module>
  File "/home/david.heward/.virtualenvs/bgc_firewall/lib/python2.7/site-packages/pandevice/base.py", line 554, in apply
    device.active().xapi.edit(self.xpath(), self.element_str(), retry_on_peer=self.HA_SYNC)
  File "/home/david.heward/.virtualenvs/bgc_firewall/lib/python2.7/site-packages/pandevice/base.py", line 3253, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError: Malformed Request
```

I suspect thats because of issues trying to start with a Vsys of None and change it to one of vsys1 when vsys1 does not already exist?

**Comment by shinmog** [comment]
@DaveHewy 

There are two problems with this code.

The first is the code handling finding the appropriate template.  You are not handling the situation of "template does not exist" properly.  As your code is, your code will march on and update the last template found in the config, whether it's the correct template or not.

The second problem, and probably where this error is coming from, is how you're doing the vsys list handling.  You have aligned the `else` statement with the `if`, which is not correct.  If you look at my code, you'll see that my `else` aligns with the `for`, so I'm only adding a single vsys.  Unindenting that `else` should probably get rid of your error.

**Comment by DaveHewy** [comment]
@shinmog 
Simply a paste error. Here's the patched code below - which does not work.

Lets try and minimise the back and forth here (as its getting a bit insane). If you wouldn't mind pasting an example of a working snippet which updates the default_vsys of a template from None to vsys1.

```
device = PanDevice.create_from_device(*auth)
template_name = 'dev'
default_vsys = 'vsys1'
templates = Template.refreshall(device)
for tmpl in templates:
    if tmpl.name == template_name:
        break
else:
   print('Template {0} not found'.format(template_name))

tmpl.default_vsys = default_vsys
if tmpl.default_vsys is not None:
    vsys_list = tmpl.findall(Vsys)
    for v in vsys_list:
        if v.name == default_vsys:
            break
    else:
        tmpl.add(Vsys(default_vsys))
tmpl.apply()
```

**Comment by DaveHewy** [comment]
@shinmog 

Thanks for the response again.

Lets just double take one more time...
I am trying to set the default_vsys of a given template from None. To vsys1. 

```
>>> fn(auth, tmpl, 'vsys1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 24, in fn
  File "/home/david.heward/.virtualenvs/bgc_firewall/lib/python2.7/site-packages/pandevice/base.py", line 554, in apply
    device.active().xapi.edit(self.xpath(), self.element_str(), retry_on_peer=self.HA_SYNC)
  File "/home/david.heward/.virtualenvs/bgc_firewall/lib/python2.7/site-packages/pandevice/base.py", line 3253, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError: Malformed Request
```

**Comment by DaveHewy** [comment]
Wonder if it has something to do with there being no managed devices under this template atm?

**Comment by shinmog** [comment]
Ok, thanks for the feedback.  Can you tell me if the template you're trying to set the default vsys for is an empty template or if it has data in it?  If it is a non-empty template, could you make a new template, leave it empty, and run the above script against that?  I'm starting to wonder if the problem lies with the fact that pandevice doesn't support everything.

Also, what version PAN-OS are you running against?

**Comment by shinmog** [comment]
I've been giving this a bit more thought.  I don't think doing `.apply()` on the template is a good idea at all.  Unless you know for sure that everything in the template config is supported by pandevice, doing `.apply()` will truncate config.

A safer approach would be to do the following instead:

1. Find the template to be updated (same as before).
2. If the vsys you want to set as the default vsys doesn't have an entry under the template, then do `.create()` on the `pandevice.device.Vsys` object (after adding it to the `pandevice.panorama.Template` object).
3. Now that we know the template has a vsys spec matching the desire default vsys, do `tmpl.update('default_vsys')` to update just the default vsys setting to the new value.

Hopefully this new approach will work out better.

**Comment by DaveHewy** [comment]
@shinmog Ok, so, good news! That does indeed work. Switching to the `tmpl.update('default_vsys')` works.

Strangely, this update() method does not work for other updates to the template. So you ultimately need to mix and match apply() and update() depending on what it is you're trying to do. Which seems a bit gross. Ultimately you should just be able to edit the `tmpl` object and run a `save()` function and the complexity be relatively hidden. Anyways, your response has helped me move forward another step, so thank you very much for that :+1: 

A grossly shortened working example:
```
v = Vsys('vsys1')
tmpl.add(v)
v.create()
tmpl.default_vsys = 'vsys1'
tmpl.update('default_vsys')
```

**Comment by shinmog** [comment]
Ok, sweet :)

Closing this issue, then.
