### ISSUE TITLE
Feature Request: Virtual Router BGP support

### ISSUE THREAD

**Issue by traittinen** [PaloAltoNetworks/pandevice#144]
Would it be possible to implement BGP support for pandevice network module. To work properly this should support adding/modifying/deleting the following attributes:

- BGP Router ID
- BGP AS Number
- BGP BFD Profile (needs to support adding BFD profiles on system level)
- BGP Peer Groups (including individual peers)
- BGP Import/Export Policies
- BGP Redistribution Rules (links to redistribution policy)

**Comment by btorresgil** [comment]
https://github.com/PaloAltoNetworks/pandevice/pull/132

**Comment by shinmog** [comment]
This is resolved as of pandevice v0.7.0
