### ISSUE TITLE
setup_requires

### ISSUE THREAD

**Issue by zendritic** [PaloAltoNetworks/pandevice#150]
As described here: https://github.com/pypa/pip/issues/410 using setup_requires is problematic for offline installs. We're mirroring pandevice in Artifactory but the server we want to install it on does not have access to the Internet. Installing pan-python succeeds but pandevice fails presumably due to setuptools attempting to download dependency info from pypi.python.org.

**Comment by ishuguru** [comment]
I also have a case where i need to install it offline, so this would be good to get solved :)

**Comment by shinmog** [comment]
@zendritic @ishuguru 

pandevice is using pytest for the test executor, and using "setup_requires" is the standard way to have `python setup.py test` run pytest:

https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner

That being said, there is a "manual integration" section which does not use "setup_requires", but instead requires setuptools.  So maybe the fix here is to try and use the manual integration first, and if the setuptools import fails, then fallback to using `setup.setup_requires` as it does today.

I just tried this out on my laptop using the repro steps you linked in the opening comment and it seems to work just fine (replacing `pip install -d....` with `pip download -d....`), and running the tests using `python setup.py test` still executes pytest fine.

I'm going to push up a branch that fixes this, it would be awesome if you two could also try it out so I know for sure it works for you sometime this week.

**Comment by zendritic** [comment]
@shinmog I apologize I didn't see your response. Thank you for resolving this!
