### ISSUE TITLE
Panorama-Template NTP Configuration

### ISSUE THREAD

**Issue by Grisha-L** [PaloAltoNetworks/pandevice#153]
Hi,

I'm attempting to set the NTP of one of the Templates within the Panorama using the following line:
`my_template.add(pandevice.device.NTPServerPrimary(address=ntp)).create()`
And I'm getting an error, it appears that the code is attempting to perform the configuration to the wrong xpath:
`/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='My-Template']/config/devices/entry[@name='localhost.localdomain']/ntp-servers`
While the actual path should be:
`/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='My-Template']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/ntp-servers/primary-ntp-server`

**Comment by shinmog** [comment]
@Grisha-L 

You have incorrectly configured your pandevice object tree.  It looks like your tree is probably this:

`panorama.Panorama` > `panorama.Template` > `device.NTPServerPrimary`

But it should be this:

`panorama.Panorama` > `panorama.Template` > `device.SystemSettings` > `device.NTPServerPrimary`

As a hint, when you are designing your pandevice object hierarchy, check each object's `CHILDTYPES` value, and that tells you what the parent/child relationships should be.

**Comment by Grisha-L** [comment]
Hi, so as I understand the `device.NTPServerPrimary' Class should be created aside and then tied to the `device.SystemSettings` Class, is that correct?
I'm having a trouble making it work, would you mind showing me how the code should look like in that case?
Thanks in advance

**Comment by shinmog** [comment]
@Grisha-L 

Sure thing.  Here's an example of me setting the primary NTP address on a new template that doesn't already exist:

```python
from pandevice.panorama import Panorama, Template
from pandevice.device import SystemSettings, NTPServerPrimary

# Authenticate
pano = Panorama('10.1.1.1', 'admin', 'password')
pano.refresh_system_info()

# Create all objects that we'll use
tmpl = Template('my new template')
ss = SystemSettings()
ntp = NTPServerPrimary(address='8.8.8.8')

# Setup pandevice object tree.
pano.add(tmpl)
tmpl.add(ss)
ss.add(ntp)

# Set the primary NTP address
ntp.create()
```

**Comment by Grisha-L** [comment]
Thanks a lot, that was very helpful 👍

**Comment by shinmog** [comment]
Seems like the issue is resolved, so closing.
