### ISSUE TITLE
Set Security Profile

### ISSUE THREAD

**Issue by EdoardoMDP** [PaloAltoNetworks/pandevice#155]
Hi all,

I'm using pandevice library.

My idea is the following:
 - for each rule with service setted to any, I would like to apply a security profile

```
fw = pandevice.firewall.Firewall(hostname=HOSTNAME, api_key=API_KEY)

rulebase = pandevice.policies.Rulebase()

fw.add(rulebase)

rules = pandevice.policies.SecurityRule.refreshall(rulebase)

for rule in rules:
       if 'any' in rule.service:
                 //set security_profile (like av,URL Filtering Profiles,Vulnerability Protection Profiles,etc...)

       rule.apply()
```

What is the method that set the security profile to a specific rule?
Thanks in advice

**Comment by shinmog** [comment]
@EdoardoMDP 

This is controlled by the following params in `pandevice.policies.SecurityRule`:

```
        group (str): Security Profile Group
        virus (str): Antivirus Security Profile
        spyware (str): Anti-Spyware Security Profile
        vulnerability (str): Vulnerability Protection Security Profile
        url_filtering (str): URL Filtering Security Profile
        file_blocking (str): File Blocking Security Profile
        wildfire_analysis (str): Wildfire Analysis Security Profile
        data_filtering (str): Data Filtering Security Profile
```

**Comment by EdoardoMDP** [comment]
@shinmog

Thanks for the answer.
I tried rule.virus but it returns the security profile.
I don’t know the function that allows me to set the profile( something like virus.set(“nane”))

**Comment by shinmog** [comment]
@EdoardoMDP 

I might not be understanding your question.

If your question is, "I have a pre-existing Anti-virus security profile that I want to add to my security rule, how do I do that," then the answer is, using your code example:

```python
for rule in rules:
    rule.virus = "my-antivirus-profile"
    rule.apply()
```

If your question is, "I'd like to configure a brand new anti-virus security profile (or modify an existing one), how do I do that?" then the answer is that modifying those profiles (antivirus, spyware, etc) are not yet supported by pandevice.

**Comment by EdoardoMDP** [comment]
Thanks so much.
I need the first one!
@shinmog

**Comment by shinmog** [comment]
Glad to help :)
