### ISSUE TITLE
Unable to delete a VR

### ISSUE THREAD

**Issue by asgharhussaindev** [PaloAltoNetworks/pandevice#160]
Hi,

I am trying to use PanDevice to delete the default virtual router, but am getting an error:

CODE:
=====
# Delete default vr
default_vr = network.VirtualRouter("default")
result = fw.delete(default_vr)

Python Error:
==========
Traceback (most recent call last):
  File "pandevicetest.py", line 30, in <module>
    result = fw.delete(default_vr)
TypeError: delete() takes 1 positional argument but 2 were given

**Comment by shinmog** [comment]
```python
from pandevice.firewall import Firewall
from pandevice.network import VirtualRouter

# Create the firewall object, fill out with your auth params.
fw = Firewall(.........)

# Create the object for the virtual router to edit.
default_vr = VirtualRouter("default")

# Add the object to our pandevice object tree.
fw.add(default_vr)

# Delete the virtual router.
default_vr.delete()
```
