### ISSUE TITLE
Having Ahard Time with Device Group add and delete

### ISSUE THREAD

**Issue by DevGumbo** [PaloAltoNetworks/pandevice#168]
I am trying to edit the existing device groups that i have on panorama but i am running into issues where it says that x is not in the list.
I imagined it had to do with the pano child state that was present in memory at time fo run so i did a pandevice.panorama.Devicegroup.refreshall()

I am then able to see the device groups that are there but i am not sure how i would remove a firewall from one of them and then add it to another one.

at this point i am able to see the device groups as children  with the following code

import pandevice as pd

pano = base.PanDevice.create_from_device()
pd.panorama.PanObject.refreshall(pano) #### Gets me a none as the child print out
pd.panorama.DeviceGroup.refreshall(pano) #### Get me a list of device groups as children under 
                                                                                    pano

now i need to remove a firewall from one of the DG and put it in a different DG.

Any assistanc would be appreciated and i am sorry if it is elementary but i have not been able to figure it out thus far from documentation alone.

**Comment by btorresgil** [comment]
Here's an example python script that would do what you want.  Comments included to explain each step.  Don't forget to perform a `pano.commit()` and `pano.commit_all()` after you've made all your changes.

```python
from pandevice.panorama import DeviceGroup, Panorama
from pandevice.firewall import Firewall


def main():
    new_dg_name = "new-device-group"
    the_serial = "12345"

    pano = Panorama("127.0.0.1", "admin", "secret")

    # Get all the device groups and firewalls
    pano.refresh_devices(add=True, expand_vsys=False)

    # Find the firewall in the list of device groups
    fw = pano.find(the_serial, Firewall, recursive=True)

    if fw is None:
        # The firewall doesn't exist
        return

    if isinstance(fw.parent, DeviceGroup) and fw.parent.name == new_dg_name:
        # The firewall is already in the device group
        return

    # Remove firewall from parent device group
    fw.delete()

    # Add firewall to target device group and create the device group if it doesn't exist
    dg = pano.find_or_create(new_dg_name, DeviceGroup)
    dg.add(fw)
    fw.create()


if __name__ == "__main__":
    main()
```
