### ISSUE TITLE
No peer_backup_ip in pandevice.ha.HighAvailability

### ISSUE THREAD

**Issue by patrickdaj** [PaloAltoNetworks/pandevice#175]
There does not appear to be a way to set the HA1 backup links peer IP.  peer_ip is available for setting HA1 peer IP but there doesn't appear to be a peer_backup_ip in order to get HA1 redundancy configuration.  Seems like this would be required in order to utilize the pandevice.ha.HA1Backup.  Without setting peer, the HA1Backup doesn't do much good.  Or am I missing something?

https://pandevice.readthedocs.io/en/latest/module-ha.html#pandevice.ha.HighAvailability

**Comment by patrickdaj** [comment]
Submitted a pull request for this.

https://github.com/PaloAltoNetworks/pandevice/pull/177

**Comment by shinmog** [comment]
Fixed by #180, thanks @patrickdaj
