### ISSUE TITLE
commit_device_and_network & commit_policy_and_objects use incorrect exclude

### ISSUE THREAD

**Issue by durgeshm** [PaloAltoNetworks/pandevice#184]
## Describe the bug

`commit_device_and_network` is using `device-and-network` in its `exclude` argument to `_commit`.
`commit_policy_and_objects` is using `policy-and-objects` in its `exclude` argument to `_commit`.

https://github.com/PaloAltoNetworks/pandevice/blob/develop/pandevice/firewall.py#L369 
https://github.com/PaloAltoNetworks/pandevice/blob/develop/pandevice/firewall.py#L373

## Expected behavior
The excludes should be switched for intended behavior.

`commit_device_and_network` should exclude `policy-and-objects`.
`commit_policy_and_objects` should exclude `device-and-network`.

**Comment by durgeshm** [comment]
https://github.com/PaloAltoNetworks/pandevice/pull/185 if it helps.

**Comment by shinmog** [comment]
Fixed by #185 - thanks @durgeshm
