### ISSUE TITLE
User defined Services, ServiceGroups, Applications, ApplicationGroups, and ApplicationFilters

### ISSUE THREAD

**Issue by lampwins** [PaloAltoNetworks/pandevice#19]
Need objects for user defined:

- Services
- Service Groups
- Applications (lower priority)
- Application Groups
- Application Filters (lower priority)

I also would like to get all of the predefined applications and services, but I know this response is large and thus slow, so maybe a not being part of the normal pandevice.refresh() but a separate call to explicitly retrieve these. Or maybe another parameter on the refresh call?

The reason for needing more than just the name of the predefined applications is to also know the standard ports. Basically I am looking to programmatically choose an appropriate (best guess) application to use in a rule, based on some set of ports given.

**Comment by lampwins** [comment]
I submitted a pull request that covers the objects for this request. It does not cover anything about the predefined applications and services. That honestly probably should have been a separate request, but nonetheless, is still functionality I am very interested in having.

**Comment by btorresgil** [comment]
Thanks for the PR, I added a review.

Agreed that retrieving predefined apps and threats from the firewall would be useful, and that it should be a separate issue.  I played around with creating a `predefined.py` module to handle this at one point but never got very far.  We'll keep working on it, let us know if you come up with anything to share.

**Comment by btorresgil** [comment]
Resolved by PR #20
