### ISSUE TITLE
New xpaths to configure Panorama servers in PAN-OS 9.1

### ISSUE THREAD

**Issue by MrDanao** [PaloAltoNetworks/pandevice#196]
## Describe the bug

Since PAN-OS 9.1, xpaths to configure Panorama servers have been modified.

## Expected behavior

In PAN-OS 9.1, xpaths are:
- Server 1 = `/config/devices/entry[@name='...']/deviceconfig/system/panorama/local-panorama/panorama-server`
- Server 2 = `/config/devices/entry[@name='...']/deviceconfig/system/panorama/local-panorama/panorama-server-2`

## Current behavior

Below PAN-OS 9.1, xpaths are:
- Server 1 = `/config/devices/entry[@name='...']/deviceconfig/system/panorama-server`
- Server 2 = `/config/devices/entry[@name='...']/deviceconfig/system/panorama-server-2`

## Affected class

[`pandevice.device.SystemSettings`](https://github.com/PaloAltoNetworks/pandevice/blob/d4804b44b20b07e66940fbae65dee3345e7a2729/pandevice/device.py#L236)

**Comment by shinmog** [comment]
Fixed by #197
