### ISSUE TITLE
Applying configuration text/commands

### ISSUE THREAD

**Issue by FliesLikeABrick** [PaloAltoNetworks/pandevice#206]
## Describe the bug

We are trying to automate the configuration of VPNs using the configuration provided by Amazon AWS or other cloud providers.  We do some strategic updates of certain values, such as our external interface netmask, next-available tunnel interfaces, etc; then print the configuration to the user.

The next step would be to automatically apply the configuration, but I do not see a way via firewall.Firewall() and other objects to apply "configure mode" configuration commands.

## Expected behavior

We would like to be able to submit configure-mode commands such as
configure
set address example-test description "this is a test"

and have the appropriate candidate configuration be staged.
  
## Current behavior

Firewall.op() does not seem to support "configure,"

## Possible solution
Point us to the appropriate documentation for op() or another means of accomplishing this task, given that we have a chunk of existing set-mode configuration to apply

## Steps to reproduce

1.  Firewall.op("configure", cmd_xml=False)

## Your Environment

- Version used:0.14.0
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): python 3.6.9
- Operating System and version (desktop or mobile): Miscellaneous Linux-alike
- Link to your project:

**Comment by btorresgil** [comment]
Hello thanks for reaching out. This package leverages the API, not the CLI, so you cannot feed arbitrary commands to it. The `Firewall.op()` method is only available for passing operational commands to the [Operational Mode Command API](https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-panorama-api/pan-os-xml-api-request-types/run-operational-mode-commands-api.html#idb894d5f5-091f-4e08-b051-4c22cc9c660d), so it does not accept Configuration Mode commands or Debug commands.

To make configuration changes, you need to use the python classes included in the library to create a configuration tree, then apply that tree to the live device. Documentation on how to do that is available in the [Getting Started Guide](https://pandevice.readthedocs.io/en/latest/getting-started.html).

There are several IPSec VPN classes available in the [network module](https://pandevice.readthedocs.io/en/latest/module-network.html) which you would add to your configuration tree.

**Comment by FliesLikeABrick** [comment]
Thanks, this is what I suspected but was not eager to take on the additional effort to parse the existing config text back into the configuration tree.
