### ISSUE TITLE
Has anyone used toggle_ha_active() ?  If so what is the syntax ?  I am trying something very easy but it won't switch the firewalls.  I am simply trying to do fw.toggle_ha_active().

### ISSUE THREAD

**Issue by wcudave17** [PaloAltoNetworks/pandevice#219]

**Comment by wcudave17** [comment]
fw = Firewall('192.168.101.133', 'admin', 'admin')
fw.set_ha_peers(Firewall('192.168.101.128', 'admin', 'admin'))
fw.toggle_ha_active()
Nothing happens when i run this.  I can however run other fw.op commands and fw.refresh_ha_active.

**Comment by btorresgil** [comment]
Here's info on how to interact with HA pairs of firewalls.
https://pandevice.readthedocs.io/en/latest/howto.html#high-availability-pairs

Let us know if anything is unclear or you have more questions.
