### ISSUE TITLE
vwire "tag_allowed" field requires a vartype of 'int'

### ISSUE THREAD

**Issue by steve-krause** [PaloAltoNetworks/pandevice#221]
When initially pulling in Panorama templates and parsing an exception is thrown if any value other than int is entered, even though a range or list of numbers are also valid input

## Describe the bug
While parsing the template the 'tag-allowed' is assigned a vartype of 'int' so the 
parse_value_from_xml_last_tag does not see valid ranges or lists such as '0-4094' as valid and raises an exception

## Expected behavior
Parsing should allow for ranges and lists such as 0-4094 , 1-10, or 5,10,20-25, etc.

## Current behavior
In base.py, within 'parse_value_from_xml_last_tag' in  the 'Do vartype processing' section
>         elif self.vartype == 'int':
>             settings[self.param] = int(elm.text)
raises an exception

## Possible solution
set the tag-allowed token to a type other than int. Possibly also test using a regex such as ^[0-9,\,,\-]+$

## Steps to reproduce
1. Create a panorama template with a vwire object with "Tag Allowed" field set to "1-5"
2. Attempt a call such as "panorama.Template.refreshall(pano)"

## Screenshots
![screenshot](https://user-images.githubusercontent.com/13668898/81211913-13ed1580-8fa2-11ea-8190-b2b8a0084965.png)

## Context
I am unable to leverage the pandevice library to manage our Panorama because it cannot successfully parse the existing configuration

## Your Environment
Panorama: 80 Templates, 60 Template Stacks, 100+ Device Groups managing a few hundred firewalls

- Panorama version 8.1.9
- Python 3.8.2
- Ubuntu 20.04:

**Comment by steve-krause** [comment]
I was able to get it to successfully parse by changing the 'tag-allowed' param from vartype 'int' to 'none' within the class VirtualWire

network.py line 571
```
        params.append(VersionedParamPath(
            'tag', path='tag-allowed', vartype='none'))
```

**Comment by rmarnold** [comment]
I'm also having this issue, is anyone working to resolve this?

**Comment by steve-krause** [comment]
> I'm also having this issue, is anyone working to resolve this?

Yesterday I created pull request 232 to remove the vartype from the tag-allowed VersionedParamPath call in network.py. Hopefully it is approved and merged soon.

As a workaround I have manually made the change on my machine and have been using it without problems for weeks now. You can probably do the same.

**Comment by btorresgil** [comment]
Thanks for opening this and for the pull request. Sorry for the slow reply.

On the surface this seems like an easy change, but we have to ensure there aren’t previous versions of PAN-OS where we’d break support. We’re confirming this through testing. It’s important to us that older scripts on older PAN-OS continue to work on the latest versions of pandevice.

Will try to get this merged in ASAP, thanks for helping us prioritize it.

**Comment by btorresgil** [comment]
Related to PR #232
