### ISSUE TITLE
how to remove an address_object from an AddressGroup?

### ISSUE THREAD

**Issue by Ronnie08** [PaloAltoNetworks/pandevice#224]
I searched all the examples and documents , and did not find any resulst.
Anyone can help me?

thanks anyway.

**Comment by btorresgil** [comment]
There's a couple ways you can do it. You can `.apply()` a new version of the address group with that address object missing, or you can `.update()` the specific variable within the address group.

Example:
```py
from pandevice.firewall import Firewall
from pandevice.objects import AddressGroup

fw = Firewall("10.0.1.1", "admin", "password")

# Create a placeholder for the AddressGroup in the config tree
addressgroup = AddressGroup('my-address-group')
fw.add(addressgroup)

# Pull the config from the live device for this address group
addressgroup.refresh()

# Make your change and apply it back to the live device
addressgroup.static_value.remove('some-address-object')
addressgroup.update('static_value')
# or, addressgroup.apply() if you have other changes to push at once
```

If you don't know the other address objects in the address group, you can do a refresh first, as in the example. But if you know what the final state should be, you can skip the refresh step and just set the `static_value` parameter yourself, then `.update()` or `.apply()` it.

```py
from pandevice.firewall import Firewall
from pandevice.objects import AddressGroup

fw = Firewall("10.0.1.1", "admin", "password")

# Create a placeholder for the AddressGroup in the config tree
addressgroup = AddressGroup('my-address-group')
fw.add(addressgroup)

# Instead of addressgroup.refresh() just set the value yourself.
addressgroup.static_value = ['keep-this-addressobject', 'keep-this-one-too']
addressgroup.update('static_value')
```

**Comment by btorresgil** [comment]
Just following up in case you have any questions on the above. We'll close this issue if not. Thanks!

**Comment by Ronnie08** [comment]
it works, thanks very much
