### ISSUE TITLE
Add support for IP wildcard mask type for address objects

### ISSUE THREAD

**Issue by chrisgoodwins** [PaloAltoNetworks/pandevice#226]
### Is your feature request related to a problem?
I'd like to be able to add or modify address objects with the type IP wildcard mask, which was introduced in PanOS version 9.0

### Describe the solution you'd like
Support added for the AddressObject class to handle the IP wildcard mask type

### Describe alternatives you've considered
Using python requests for API calls to create/modify these types of objects

**Comment by btorresgil** [comment]
Sounds good! We'll look into adding this.
