### ISSUE TITLE
Assign router and zone to Layer3Subinterface?

### ISSUE THREAD

**Issue by xod442** [PaloAltoNetworks/pandevice#240]
Adding layer 3 subinterface works great but I can't seem to figure out how to get the router and zone applied. I looked in the network.py and it doesn't appear to be part of the method.

**Comment by btorresgil** [comment]
The router and zone are configured on the [VirtualRouter](https://pandevice.readthedocs.io/en/latest/module-network.html#pandevice.network.VirtualRouter) object and [Zone](https://pandevice.readthedocs.io/en/latest/module-network.html#pandevice.network.Zone) object. They reference the interface to create the association. This is different than the way it works in the GUI.

To make things easier, we created the convenience methods `set_virtual_interface()` and `set_zone()` you can call on the interface object.

https://pandevice.readthedocs.io/en/latest/module-network.html#pandevice.network.Interface.set_virtual_router

**Comment by xod442** [comment]
Perfect! I am just getting started with Palo Alto are there any examples of how I call these methods? Sorry for the noob Q.

**Comment by xod442** [comment]
I think I'm close but still not working... 
eth = network.Layer3Subinterface(name, tag, ip)
security_zone = network.Interface.set_zone(eth,zone)

I get this...raise err.PanDeviceNotSet("No PanDevice set for object tree")

I am working on a GUI application that will allow PA customers to bulk load layer3 IP subinterfaces. I promise I will share...I just need to get past this part. My customer has over 12 PA-500's and they need to put over 250 L3 subinterfaces on each one.  

I think you are my only hope. I'll keep hacking....thanks!

**Comment by xod442** [comment]
I got it working. Sorry to be a pest
