### ISSUE TITLE
Not seeing comments on layer3 sub-interfaces---hit submit too fast plesee delete this issue...

### ISSUE THREAD

**Issue by xod442** [PaloAltoNetworks/pandevice#241]
## Describe the bug

I use the layer3 subinterface method in pandevice library and pass several variables to it. They all show up in the GUI except for the comment. 

## Expected behavior

When I pass the comment variable via python, I expect the comment to show up in the sub interface details in the GUI 

## Current behavior

The comment field never changes. It is always blank

## Possible solution

Every other variable I pass gets added to the interface and shows up in the GUI

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by btorresgil** [comment]
Thanks for the bug report. Can you include the steps to reproduce (like a code sample) and the version of PAN-OS you’re using? Thanks!

**Comment by xod442** [comment]
Error submitting...closing.
