### ISSUE TITLE
SecurityRule 'any' attributes inconsistent behavior

### ISSUE THREAD

**Issue by lampwins** [PaloAltoNetworks/pandevice#34]
`policies.SecurityRule` has certain attributes that default to the string value 'any'. However when a SecurityRule is created from a live device and that rule has attributes actually set to 'any' the value is represented as a list `['any']`. This is inconsistent behavior and leads the developer to add extra checks to deal with these attributes when their value is actually set to 'any'.

**Comment by shinmog** [comment]
We have to set the defaults to the string `any` as opposed to the list `['any', ]` because lists are mutable.  And having mutable default arguments leads to issues later on.

Generally speaking, we angle pandevice towards being more user friendly than friendly towards pandevice contributors / autors :)

**Comment by lampwins** [comment]
I agree on both counts. What I am saying is that when a security rule is created from a live device and the attribute's value is `any` it should be represented as a string like the default value states, not as the list `['any']` as it is today.

**Comment by shinmog** [comment]
Yeah, this is a gray area.  Allowing a string or list as input, but always having a list response is a little weird.  But then again, if we did change how we handled a response of "any", then this means that user's scripts would have to also always be checking if the response is the string "any" or a list of non-`any` strings.  This seems like a step backwards in the simplicity / usability department.

**Comment by lampwins** [comment]
I agree that the user/dev should not have to deal with this. Perhaps implementing `append()` and `remove()` on these params explicitly in the library could solve it. It could then silently handle the conversion on its own.

**Comment by shinmog** [comment]
Sorry for the delayed response on this:  I am less confident that I understand what you're trying to say.  Is this an issue or an enhancement that you have in mind?  It seems we're in agreement that the user-side should stay as having `SecurityRule`s have `['any', ]` as the value..?  So is what you're referring to something that would be internal facing only..?

**Comment by lampwins** [comment]
The issue is currently, the difference in creating a new `SecurityRule` in the library vs loading one from a live device. In the former, the default value is the string `'any'` and in the latter, it is the list `['any', ]`. 

What I proposed was an enhancement to potentially solve this. By quietly doing the conversion in the library, the user no longer has to care if the value is a string or a list, they will always treat it like a list interface.

**Comment by btorresgil** [comment]
Talked with @shinmog and we agree with you, the intended convenience of working with a string results in an inconsistent behavior that is confusing.  Marking as a bug and will fix.
