### ISSUE TITLE
Support bulk operations in pandevice

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/pandevice#44]
Define a new kind of object that contains other PanObjects.  This container itself does not generate xpath or xml like a PanObject does, but if `create()` or another method like it is called on the container, this would cause the children of the container to be created in an optimized way.

This container object would also handle situations such as namespaces, for example, the shared namespace could be handled with a container object.

**Comment by shinmog** [comment]
Updating bug description to more accurately match the problem:  pandevice needs a way to do bulk operations.
