### ISSUE TITLE
dyn_address_group.py: error: unrecognized arguments: General

### ISSUE THREAD

**Issue by irom77** [PaloAltoNetworks/pandevice#47]
Hi I am trying to tag existing IP 10.34.20.94 on firewall 10.34.2.21 (PANOS 7.1.7 - model 5060 multi vsys) with tag General , getting error below:

```
$ python dyn_address_group.py 10.34.2.21 admin 'password' 10.34.20.94 General
usage: dyn_address_group.py [-h] [-v] [-q] [-r REGISTER] [-u UNREGISTER] [-l]
                            [-c]
                            hostname username password ip
dyn_address_group.py: error: unrecognized arguments: General
```

I am using pandevice (0.3.5)

**Comment by shinmog** [comment]
Huh..  Seems there are two problems here.  First is that if you want to register a tag, you should give the tag using the `-r` flag.  So in your example:

`python dyn_address_group.py -r General 10.34.2.21 admin password 10.34.20.94`

Now the second problem is that when you change your command to work like that, this script still won't work because there is a combination of script errors and attempts to use functions that don't exist (likely these got renamed between when this script was created and now).

**Comment by irom77** [comment]
The tag General exists, how I can use dyn_address_group.py to assign this tag to address object ?

**Comment by btorresgil** [comment]
Keep in mind there are different kinds of tags on the firewall.  This is not referring to the tag object you configure via the GUI.  It is referring to registered-ip tags which are configured as a match criteria in a dynamic address group.  The results of the script are visible with the CLI command: `show object registered-ip all`.  The tag does not have to be created on the firewall for you to register it with this script.

**Comment by irom77** [comment]
Got it now, it worked now with -r option. I registered two tags, "ECMP-bypass" which was previously setup in GUI and new tag "ECMP-no"

```
admin@MR-DC2-PFWP03> show object registered-ip ip 104.209.190.8

registered IP                             Tags
----------------------------------------  -----------------

104.209.190.8 #
                                         "ECMP-bypass"
                                         "ECMP-no"

Total: 1 registered addresses
*: received from user-id agent  #: persistent
```

Now not sure if I should expect dynmaic group g-ECMP-bypass-TP to include that 104.209.190.8 based on 'ECMP-no' tag ? It does not

```
admin@MR-DC2-PFWP03> show object dynamic-address-group name g-ECMP-bypass-TP
Dynamic address groups in vsys vsys1:
----------------------------------------------------

----------------defined in vsys --------------------
        g-ECMP-bypass-TP
                filter: 'ECMP-no' 
                members: total 0

O: address object; R: registered ip; D: dynamic group; S: static group

```

**Comment by irom77** [comment]
I noticed that it is fine after some time, I can see that IP address 104.209.190.8 with registered tag "ECMP-no" in dynamic address group g-ECMP-bypass-TP.. last question , can I register any object , i.e.  subnet ?

**Comment by btorresgil** [comment]
Hi @irom77, glad to hear it is working for IP addresses.  It is currently not possible to register a subnet on PAN-OS.  You can register IP addresses only.  If you need to register many IP addresses, you can do this all in one API call using the `batch_start()` and `batch_end()` methods.  Let us know if you need anything else.  Thanks!

**Comment by ncostanzo** [comment]
> Hi @irom77, glad to hear it is working for IP addresses. It is currently not possible to register a subnet on PAN-OS. You can register IP addresses only. If you need to register many IP addresses, you can do this all in one API call using the `batch_start()` and `batch_end()` methods. Let us know if you need anything else. Thanks!

Hi @btorresgil , 

Slight newbie here, with a slight newbie question for you regarding being able to register a subnet on PAN-OS. Is this now possible? We're being asked to build a dynamic address group based off subnets of AWS and trying to find a way to accomplish this with some scripting but read your previous notes where this was not currently possible in PAN-OS (maybe in ver 7.x.x ?).

Thanks,
Nick
