### ISSUE TITLE
Make vsys=None act like vsys="shared"

### ISSUE THREAD

**Issue by shinmog** [PaloAltoNetworks/pandevice#73]
Doing `vsys="shared"` should raise a Warning to use `None`.

**Comment by btorresgil** [comment]
Resolved by 94a75852c50e71cc4ca856a7d8d89038e60b9310 and #74 

vsys="shared" is not deprecated, it represents the 'shared' vsys with xpath of `/config/shared`.  A Firewall or a Vsys object can have the vsys "shared" and be considered the shared vsys.
