### ISSUE TITLE
Objects with ROOT == Root.VSYS don't have an xpath of /config/shared/

### ISSUE THREAD

**Issue by shinmog** [PaloAltoNetworks/pandevice#96]
If you have a Panorama object with an AddressObject child, then call the AddressObject’s `xpath()` method, you end up with an xpath with a vsys.  I would expected that to create an xpath such as `/config/shared/address/entry...etc`

**Comment by lampwins** [comment]
@shinmog did anything ever come of this?

**Comment by shinmog** [comment]
I'm updating all of the xpath stuff right now to support templates, so I'll address this then as well.
